version: "2"  # Docker Compose file version

# Define services
services:

  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Zookeeper image
    environment:  # Environment variables
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181  # Map host port to container port

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest  # Kafka image
    depends_on:  # Service dependencies
      - zookeeper
    ports:
      - 29092:29092  # Map host port to container port
    environment:  # Environment variables
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

  # Kafka UI service
  kafka-ui:
    container_name: kafka-ui  # Container name
    image: provectuslabs/kafka-ui:latest  # Kafka UI image
    ports:
      - 8080:8080  # Map host port to container port
    depends_on:  # Service dependencies
      - kafka
    environment:  # Environment variables
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

# Define volumes
volumes:
  kafka_data:  # Volume for Kafka data
    driver: local  # Local volume driver